name: 'hehe'
on:
  pull_request:
    branches:
      - main
# 2
jobs:
  hehe:
    if: ${{ !startsWith( github.head_ref || github.ref_name, 'revert') }}
    name: hehe
    runs-on: ubuntu-latest

    steps:
      - name: Elo
        shell: bash
        env:
            BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
        run: |
            echo "elo"
            

